now support scilab 5 except man pages

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -875,12 +875,13 @@ F77
 FFLAGS
 ac_ct_F77
 LIBTOOL
+has_scilab
 has_xsltproc
 has_sablotron
-has_scilab
 TOOLBOXDIR
 SCIDIR
 SCIEXE
+HELPDIR
 PKG_CONFIG
 OPENCV_CFLAGS
 OPENCV_LIBS
@@ -4459,7 +4460,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4462 "configure"' > conftest.$ac_ext
+  echo '#line 4463 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7516,11 +7517,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7519: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7520: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7523: \$? = $ac_status" >&5
+   echo "$as_me:7524: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7806,11 +7807,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7809: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7810: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7813: \$? = $ac_status" >&5
+   echo "$as_me:7814: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7910,11 +7911,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7913: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7914: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7917: \$? = $ac_status" >&5
+   echo "$as_me:7918: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10287,7 +10288,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10290 "configure"
+#line 10291 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10387,7 +10388,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10390 "configure"
+#line 10391 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12788,11 +12789,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12791: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12792: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12795: \$? = $ac_status" >&5
+   echo "$as_me:12796: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12892,11 +12893,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12895: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12896: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12899: \$? = $ac_status" >&5
+   echo "$as_me:12900: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14490,11 +14491,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14493: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14494: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14497: \$? = $ac_status" >&5
+   echo "$as_me:14498: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14594,11 +14595,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14597: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14598: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14601: \$? = $ac_status" >&5
+   echo "$as_me:14602: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16814,11 +16815,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16817: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16818: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16821: \$? = $ac_status" >&5
+   echo "$as_me:16822: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17104,11 +17105,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17107: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17108: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17111: \$? = $ac_status" >&5
+   echo "$as_me:17112: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17208,11 +17209,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17211: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17212: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17215: \$? = $ac_status" >&5
+   echo "$as_me:17216: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19907,124 +19908,8 @@ then
 fi
 
 
-###
-### Tests for windows
-###
-##native_win32_build='no'
-##cygwin_build='no'
-##win32_build='no'
-##case $host_os in
-##   cygwin*)
-##       cygwin_build='yes'
-##       win32_build='yes'
-##       ;;
-##   mingw* )
-##       native_win32_build='yes'
-##       win32_build='yes'
-##       ;;
-##esac
-
-
-# checks for xsltproc (to buld HTML help pages)
-# Extract the first word of "xsltproc", so it can be a program name with args.
-set dummy xsltproc; ac_word=$2
-{ echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_prog_has_xsltproc+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$has_xsltproc"; then
-  ac_cv_prog_has_xsltproc="$has_xsltproc" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_prog_has_xsltproc="yes"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-IFS=$as_save_IFS
-
-  test -z "$ac_cv_prog_has_xsltproc" && ac_cv_prog_has_xsltproc="no"
-fi
-fi
-has_xsltproc=$ac_cv_prog_has_xsltproc
-if test -n "$has_xsltproc"; then
-  { echo "$as_me:$LINENO: result: $has_xsltproc" >&5
-echo "${ECHO_T}$has_xsltproc" >&6; }
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
-
-if test x$has_xsltproc = xno; then
-   # checks for sabcmd as an alternative
-   # Extract the first word of "sabcmd", so it can be a program name with args.
-set dummy sabcmd; ac_word=$2
-{ echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_prog_has_sablotron+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$has_sablotron"; then
-  ac_cv_prog_has_sablotron="$has_sablotron" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_prog_has_sablotron="yes"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-IFS=$as_save_IFS
-
-  test -z "$ac_cv_prog_has_sablotron" && ac_cv_prog_has_sablotron="no"
-fi
-fi
-has_sablotron=$ac_cv_prog_has_sablotron
-if test -n "$has_sablotron"; then
-  { echo "$as_me:$LINENO: result: $has_sablotron" >&5
-echo "${ECHO_T}$has_sablotron" >&6; }
-else
-  { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
-
-   if test x$has_sablotron = xno; then
-      { { echo "$as_me:$LINENO: error: xsltproc or sabcmd programs were not found but \
-at least one of them is required to build the SIVP manual pages.
-Download xslproc (from libxml) at:
-   http://www.xmlsoft.org
-or sabcmd (from sablotron) at:
-   http://www.gingerall.com/charlie/ga/xml/p_sab.xml" >&5
-echo "$as_me: error: xsltproc or sabcmd programs were not found but \
-at least one of them is required to build the SIVP manual pages.
-Download xslproc (from libxml) at:
-   http://www.xmlsoft.org
-or sabcmd (from sablotron) at:
-   http://www.gingerall.com/charlie/ga/xml/p_sab.xml" >&2;}
-   { (exit 1); exit 1; }; }
-   fi
-fi
-
-# test if SCI is defined. If not, test if scilab is in path,
-# then get SCI from scilab -nw.
-if test -z "$SCI"; then
-   # Extract the first word of "scilab", so it can be a program name with args.
+# check for Scilab
+# Extract the first word of "scilab", so it can be a program name with args.
 set dummy scilab; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
@@ -20062,31 +19947,141 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
-   if test x$has_scilab = xno; then
-      { { echo "$as_me:$LINENO: error: neither Scilab was found in your PATH nor a SCI variable has been defined" >&5
-echo "$as_me: error: neither Scilab was found in your PATH nor a SCI variable has been defined" >&2;}
+if test x$has_scilab = xno; then
+    { { echo "$as_me:$LINENO: error: scilab binary program was found in your PATH, your PATH is $PATH" >&5
+echo "$as_me: error: scilab binary program was found in your PATH, your PATH is $PATH" >&2;}
    { (exit 1); exit 1; }; }
-   else
-      cmd='F=mopen("path.incl","w");
+fi
+SCIEXE="scilab"
+# test if SCI is defined. If not, test if scilab is in path,
+# then get SCI from scilab -nwni.
+if test -z "$SCI"; then
+      cmd='F=mopen("getpath.incl","w");
            mfprintf(F,SCI);
-           mclose(F);'
-      echo "$cmd" | scilab -nw >/dev/null
-      SCIDIR=`cat path.incl`
-	 # TODO
-	 #SCIEXE="${SCIDIR}/bin/scilex"
-	 SCIEXE="${SCIDIR}/bin/scilab"
-   fi
+           mclose(F);exit;'
+      echo "$cmd" > getpath.sci
+      scilab -nw -f getpath.sci >/dev/null
+      SCIDIR=`cat getpath.incl`
+      rm -f getpath.sci getpath.incl
 else
    SCIDIR="$SCI"
-   if test $win32_build = yes; then
-      SCIEXE="${SCI}/bin/Scilex.exe"
-   else
-      #SCIEXE="${SCI}/bin/scilex"
-      SCIEXE="${SCI}/bin/scilab"
-   fi
 fi
 
-#CFLAGS="$CFLAGS -I${SCIDIR}/routines"
+#get scilab version
+cmd='F=mopen("version.incl","w");
+     ver=getversion();
+     ver=part(ver, 8);
+     mfprintf(F,ver);
+     mclose(F);exit;'
+echo "$cmd" > version.sci
+scilab -nwni -f version.sci >/dev/null
+SCIVERSION=`cat version.incl`
+rm -f version.sci version.incl
+
+echo "Scilab version is $SCIVERSION"
+
+HELPDIR=""
+if test $SCIVERSION -le 4; then
+   # checks for xsltproc (to buld HTML help pages)
+   # Extract the first word of "xsltproc", so it can be a program name with args.
+set dummy xsltproc; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_has_xsltproc+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$has_xsltproc"; then
+  ac_cv_prog_has_xsltproc="$has_xsltproc" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_has_xsltproc="yes"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_prog_has_xsltproc" && ac_cv_prog_has_xsltproc="no"
+fi
+fi
+has_xsltproc=$ac_cv_prog_has_xsltproc
+if test -n "$has_xsltproc"; then
+  { echo "$as_me:$LINENO: result: $has_xsltproc" >&5
+echo "${ECHO_T}$has_xsltproc" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+   if test x$has_xsltproc = xno; then
+      # checks for sabcmd as an alternative
+         # Extract the first word of "sabcmd", so it can be a program name with args.
+set dummy sabcmd; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_has_sablotron+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$has_sablotron"; then
+  ac_cv_prog_has_sablotron="$has_sablotron" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_has_sablotron="yes"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_prog_has_sablotron" && ac_cv_prog_has_sablotron="no"
+fi
+fi
+has_sablotron=$ac_cv_prog_has_sablotron
+if test -n "$has_sablotron"; then
+  { echo "$as_me:$LINENO: result: $has_sablotron" >&5
+echo "${ECHO_T}$has_sablotron" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+         if test x$has_sablotron = xno; then
+                  { { echo "$as_me:$LINENO: error: xsltproc or sabcmd programs were not found but \
+                   at least one of them is required to build the SIVP manual pages.
+                   Download xslproc (from libxml) at:
+                     http://www.xmlsoft.org
+                   or sabcmd (from sablotron) at:
+                     http://www.gingerall.com/charlie/ga/xml/p_sab.xml" >&5
+echo "$as_me: error: xsltproc or sabcmd programs were not found but \
+                   at least one of them is required to build the SIVP manual pages.
+                   Download xslproc (from libxml) at:
+                     http://www.xmlsoft.org
+                   or sabcmd (from sablotron) at:
+                     http://www.gingerall.com/charlie/ga/xml/p_sab.xml" >&2;}
+   { (exit 1); exit 1; }; }
+         fi
+    fi
+    HELPDIR="man"
+else
+    HELPDIR=""
+fi
+
 
 
 
@@ -20099,6 +20094,7 @@ fi
 TOOLBOXDIR=$prefix
 
 # Set the default installation
+
 
 
 
@@ -21973,12 +21969,13 @@ F77!$F77$ac_delim
 FFLAGS!$FFLAGS$ac_delim
 ac_ct_F77!$ac_ct_F77$ac_delim
 LIBTOOL!$LIBTOOL$ac_delim
+has_scilab!$has_scilab$ac_delim
 has_xsltproc!$has_xsltproc$ac_delim
 has_sablotron!$has_sablotron$ac_delim
-has_scilab!$has_scilab$ac_delim
 TOOLBOXDIR!$TOOLBOXDIR$ac_delim
 SCIDIR!$SCIDIR$ac_delim
 SCIEXE!$SCIEXE$ac_delim
+HELPDIR!$HELPDIR$ac_delim
 PKG_CONFIG!$PKG_CONFIG$ac_delim
 OPENCV_CFLAGS!$OPENCV_CFLAGS$ac_delim
 OPENCV_LIBS!$OPENCV_LIBS$ac_delim
@@ -21988,7 +21985,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 20; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 21; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
